require 'open-uri'
require 'nokogiri'
require 'pry'
#require 'awesome_print'
require_relative "./nfl_injuries/version"
require_relative './nfl_injuries/cli'
require_relative './nfl_injuries/teams'
require_relative './nfl_injuries/player'
require_relative './nfl_injuries/scraper'
